services:
  selftorch:
    image: ghcr.io/puregavin/unsloth4arm:latest
    container_name: unsloth4arm
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./work:/work
    working_dir: /work
    gpus: all
